name: Continuous Integration

on:
  push:
    branches:
      - 'develop'
      - 'master'
      - 'feature/add-github-actions-workflow'

  pull_request:
    branches:
      - 'develop'
      - 'master'

jobs:
  install_dependencies_and_run_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.6.0

      - run: gem install bundler

      - run: bin/setup

      - run: bundle exec rspec --profile 10 --format progress
